### ISSUE TITLE
MQTT External Broker example in docs?

### ISSUE THREAD

**Issue by d2inco** [zaknye/xcel_itron2mqtt#37]
Any chance you could either make the MQTT Broker part of the Configuration UI, or alternatively, give an example of the 4 entries needed to get it up and running?   I was able to locate a 'mqtt_server_address' and 'mqtt_port' in the error message and tried those, but still need to be able to get the MQTT User/Pass in there, as well

Thank you!

**Comment by zaknye** [comment]
That's pretty confusing. So the variables used within the python program are `mqtt_server_address` and `mqtt_port`. These are however not set using those names. The environment variable `MQTT_SERVER` must be set, which will be assigned to `mqtt_server_address`. If you're running with docker, this is set with the `-e MQTT_SERVER=<your IP>` argument, which sets an environment variable internally to the container. Otherwise, if you're running it on Linux natively, you can `export MQTT_SERVER=<your IP>` to set the environment variable. You had me second guessing my naming scheme, but I'll stick to the `MQTT_SERVER` name for clarity and brevity.

The full command would look like:
```
docker run --rm -d \
    --net host \
    -e MQTT_SERVER=<IP_ADDRESS> \
    -v <path_to_cert_folder>:/opt/xcel_itron2mqtt/certs \
    ghcr.io/zaknye/xcel_itron2mqtt:main
```

**Comment by d2inco** [comment]
My apologies - I had typed this out on my laptop, so the "Configuration UI" part doesn't make sense.  It should have been under the https://github.com/wingrunr21/hassio-xcel-itron-mqtt repo.   Sorry about that; I shouldn't do tech-work on the Tablet!
